<Container>:

    text_input: text_input
    label_widget: label
    rows:3
    BoxLayout:
        orientation: 'vertical'
        MDScreen:
            CustomMDTextField:
                multiline: True
                hint_text: "Rectangle mode"
                mode: "rectangle"
                id: label
                readonly: True
                size_hint: 1, 1
                padding: (10, 10)
                text: "Hey Im ChatGPT just send me a message and wait (a little)"


    FloatLayout:
        size_hint: 1, 0.3
        TextInput:
            size_hint: 1, 0.85
            id: text_input
        MDScreen:

            MDRaisedButton:
                text: "Go"
                size_hint: 0.2, 0.85
                pos_hint: {"center_x":0.9}
                background_normal: ''
                md_bg_color: app.theme_cls.primary_dark
                on_release:
                    root.change_text()